/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VirtualPetGameGUI;

import java.awt.Graphics;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;
import java.util.StringTokenizer;



/**
 *
 * @author jessi
 */
public class MainMenu extends javax.swing.JFrame {
    
   Animal pet;
   private final HashMap<String, PetUser> users;
   private final String fileName;
   
    /**
     * Creates new form MainMenu
     */
    public MainMenu(){
        initComponents();
        this.fileName = "./src/PetUsers.txt";
        this.users = new HashMap();
        this.getPetUsers(fileName);
    }

    public final void getPetUsers(String fn){
        FileInputStream fin;
        try{
            fin = new FileInputStream(fn);
            Scanner fileScanner = new Scanner(fin);
            
            while(fileScanner.hasNextLine()){
                String line = fileScanner.nextLine();
                StringTokenizer st = new StringTokenizer(line);
                PetUser u = new PetUser(st.nextToken(), Integer.parseInt(st.nextToken()));
                this.users.put(u.getUsername(), u);
            }
            fin.close();
        }catch (FileNotFoundException ex){
            System.out.println(ex.getMessage());
        }catch (IOException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void updateScore(PetUser user) {
        this.users.put(user.getUsername(), user);
        //uses arraylist to output highest score in the collection
        List<Integer> list = new ArrayList<>();
        try{
            FileOutputStream fOut = new FileOutputStream(this.fileName);
            try (PrintWriter pw = new PrintWriter(fOut)) {
                for(PetUser u : this.users.values()){
                    list.add(u.getScore());
                    pw.println(u.getUsername() + " " + u.getScore());
                }
            }
        }catch(FileNotFoundException ex){
            System.out.println(ex.getMessage());
        }
        user.setHighestScore(Collections.max(list));
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TitleLabel = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        animalComboBox = new javax.swing.JComboBox<>();
        petText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        petTextArea = new javax.swing.JTextArea();
        endButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Pet Game Simulator");
        setBackground(new java.awt.Color(204, 255, 153));
        setForeground(new java.awt.Color(255, 204, 0));

        TitleLabel.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        TitleLabel.setText("Virtual Pet Game");

        helloLabel.setBackground(new java.awt.Color(51, 255, 153));
        helloLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        helloLabel.setText("Welcome to the Virtual Pet Game");

        menuButton.setBackground(new java.awt.Color(255, 153, 102));
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        questionLabel.setText("Please choose your Pet");

        animalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat", "Rabbit" }));
        animalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalComboBoxActionPerformed(evt);
            }
        });

        petText.setText("Awaiting pet choice....");
        petText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petTextActionPerformed(evt);
            }
        });

        petTextArea.setColumns(20);
        petTextArea.setRows(5);
        jScrollPane2.setViewportView(petTextArea);

        endButton.setBackground(new java.awt.Color(255, 51, 0));
        endButton.setText("End");
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("What would you like to do with your Pet?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feed", "Play", "Clean", "Train", "Perform" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTextField1.setText("Bob");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Red");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pet Name:");

        jLabel3.setText("Pet Color:");

        jRadioButton1.setText("Option 1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Option 2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Option 3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setText("Pet Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setText("Player");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Player Name:");

        jTextField3.setText("enter name");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                            .addComponent(jScrollPane5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(30, 30, 30)
                                                .addComponent(jButton1))
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(questionLabel)
                                        .addGap(62, 62, 62)
                                        .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(petText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(helloLabel)
                                        .addGap(26, 26, 26)
                                        .addComponent(menuButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(TitleLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(helloLabel)
                            .addComponent(menuButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(petText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        Manual.main();
   
    }//GEN-LAST:event_menuButtonActionPerformed

    private void animalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalComboBoxActionPerformed
        // TODO add your handling code here:
        //ImageIcon dogIcon = new ImageIcon("images/dog image.jpg");
        if("Dog".equals(animalComboBox.getSelectedItem().toString())){
            petText.setText("Congratulations! You chose a Pet Dog!");
            petTextArea.setText("              _=,_\n" +
                                       "           o_/6 /#\\\n" +
                                       "           \\__ |##/\n" +
                                       "            ='|--\\\n" +
                                       "              /   #'-.\n" +
                                       "              \\#|_   _'-. /\n" +
                                       "               |/ \\_( # |\" \n" +
                                       "              C/ ,--___/");     
            String nameDog = jTextField1.getText().trim();
            String colorDog = jTextField2.getText().trim();

            this.pet = new Dog(nameDog, colorDog);
            petTextArea.append("\nYour puppy details:");
            petTextArea.append("\n" + pet.getanimalName());
            petTextArea.append("\n" + pet.getColour());
            jTextArea3.setText("\n" + pet.printInfo());
    
        }
        if("Cat".equals(animalComboBox.getSelectedItem().toString())){
            petText.setText("Congratulations! You chose a Pet Cat!");
            petTextArea.setText(" _._     _,-'\"\"`-._\n" +
                                       "(,-.`._,'(       |\\`-/|\n" +
                                       "    `-.-' \\ )-`( , o o)\n" +
                                       "          `-    \\`_`\"'-");
            String nameCat = jTextField1.getText().trim();
            String colorCat = jTextField2.getText().trim();

            this.pet = new Cat(nameCat, colorCat);
            petTextArea.append("\nYour kitten details:");
            petTextArea.append("\n" + pet.getanimalName());
            petTextArea.append("\n" + pet.getColour());
            jTextArea3.setText("\n" + pet.printInfo());
        }
        if("Rabbit".equals(animalComboBox.getSelectedItem().toString())){
            petText.setText("Congratulations! You chose a Pet Rabbit!");
            petTextArea.setText("       _\n" +
                                       "      (\\\\\n" +
                                       "       \\||\n" +
                                       "     __(_\";\n" +
                                       "    /    \\\n" +
                                       "   {}___)\\)_");
            String nameRabbit = jTextField1.getText().trim();
            String colorRabbit = jTextField2.getText().trim();

            this.pet = new Rabbit(nameRabbit, colorRabbit);
            petTextArea.append("\nYour rabbit details:");
            petTextArea.append("\n" + pet.getanimalName());
            petTextArea.append("\n" + pet.getColour());
            jTextArea3.setText("\n" + pet.printInfo());
        }
             
        
    }//GEN-LAST:event_animalComboBoxActionPerformed

    private void petTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petTextActionPerformed

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_endButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        if("Feed".equals(jComboBox1.getSelectedItem().toString())){
            jTextArea2.setText("What would you like to feed " + pet.animalName
                            + "\nOptions are:\n"
                            + "1. Basic Food: $2\n"
                            + "2. Intermediate Food: $4\n"
                            + "3. Luxury Food: $6");
        }
        if("Clean".equals(jComboBox1.getSelectedItem().toString())){
            jTextArea2.setText("How would you like to Clean " + pet.animalName
                            + "\nOptions are:\n"
                            + "1. Basic Cleaning\n"
                            + "2. Intermediate Cleaning\n"
                            + "3. Luxury Cleaning");
        }
        if("Play".equals(jComboBox1.getSelectedItem().toString())){
            jTextArea2.setText("How would you like to Play with " + pet.animalName
                            + "\nOptions are:\n"
                            + "1. Basic Fun\n"
                            + "2. Intermediate Fun\n"
                            + "3. Luxury Fun");
        }
        if("Train".equals(jComboBox1.getSelectedItem().toString())){
            jTextArea2.setText("How would you like to Train " + pet.animalName
                            + "\nOptions are:\n"
                            + "1. Basic Training\n"
                            + "2. Intermediate Training\n"
                            + "3. Luxury Training");
        }
        if("Perform".equals(jComboBox1.getSelectedItem().toString())){
            jTextArea2.setText("What act would you and " + pet.animalName + " like to perform"
                            + "\nOptions are:\n"
                            + "1. Basic Show\n"
                            + "2. Intermediate Show\n"
                            + "3. Advanced Show");
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        jTextArea4.setText("");
        if(animalComboBox.isShowing() == true){
            jTextArea2.setText("Please select a Pet!");
        }
        
        if(null != jComboBox1.getSelectedItem().toString())
           switch (jComboBox1.getSelectedItem().toString()) {
           case "Feed":
               Feed feed = new Feed(pet, 1);
               jTextArea2.setText(feed.feedPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Clean":
               Clean clean = new Clean(pet, 1);
               jTextArea2.setText(clean.cleanPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Play":
               Play play = new Play(pet, 1);
               jTextArea2.setText(play.playPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Train":
               Train train = new Train(pet, 1);
               jTextArea2.setText(train.trainPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Perform":
               Perform perform = new Perform(pet, 1);
               jTextArea2.setText(perform.performPet());
               jTextArea3.setText(pet.printInfo());
               break;
           default:
               break;
       }
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jTextArea4.append(pet.checkHygiene(pet));
        jTextArea4.append(pet.checkHunger(pet));
        jTextArea4.append(pet.checkHappiness(pet));
        jTextArea3.setText(pet.printInfo());
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        jTextArea4.setText("");
        if(animalComboBox.isShowing() == true){
            jTextArea2.setText("Please select a Pet!");
        }
        
        if(null != jComboBox1.getSelectedItem().toString())
           switch (jComboBox1.getSelectedItem().toString()) {
           case "Feed":
               Feed feed = new Feed(pet, 2);
               jTextArea2.setText(feed.feedPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Clean":
               Clean clean = new Clean(pet, 2);
               jTextArea2.setText(clean.cleanPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Play":
               Play play = new Play(pet, 2);
               jTextArea2.setText(play.playPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Train":
               Train train = new Train(pet, 2);
               jTextArea2.setText(train.trainPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Perform":
               Perform perform = new Perform(pet, 2);
               jTextArea2.setText(perform.performPet());
               jTextArea3.setText(pet.printInfo());
               break;
           default:
               break;
       }
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
        jTextArea4.append(pet.checkHygiene(pet));
        jTextArea4.append(pet.checkHunger(pet));
        jTextArea4.append(pet.checkHappiness(pet));
        jTextArea3.setText(pet.printInfo());
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

        jTextArea4.setText("");
        if(animalComboBox.isShowing() == true){
            jTextArea2.setText("Please select a Pet!");
        }
        
        if(null != jComboBox1.getSelectedItem().toString())
           switch (jComboBox1.getSelectedItem().toString()) {
           case "Feed":
               Feed feed = new Feed(pet, 3);
               jTextArea2.setText(feed.feedPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Clean":
               Clean clean = new Clean(pet, 3);
               jTextArea2.setText(clean.cleanPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Play":
               Play play = new Play(pet, 3);
               jTextArea2.setText(play.playPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Train":
               Train train = new Train(pet, 3);
               jTextArea2.setText(train.trainPet());
               jTextArea3.setText(pet.printInfo());
               break;
           case "Perform":
               Perform perform = new Perform(pet, 3);
               jTextArea2.setText(perform.performPet());
               jTextArea3.setText(pet.printInfo());
               break;
           default:
               break;
       }
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextArea4.append(pet.checkHygiene(pet));
        jTextArea4.append(pet.checkHunger(pet));
        jTextArea4.append(pet.checkHappiness(pet));
        jTextArea3.setText(pet.printInfo());
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //new GUI("Pet Report",("Thank you for playing Virtual Pet Game" + pet.printInfo()));
//        String petReport = (pet.printInfo());
//        new GUI("Pet Report",petReport);
        
            
          PetReport.main(pet);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if("enter name".equals(jTextField3.getText())){
           jTextArea2.setText("Please enter a player name!");
       }else{
       PetUser user = new PetUser(jTextField3.getText(), pet.getPetScore());
       updateScore(user);
       PetUser.main main;
       main = new PetUser.main(user);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JComboBox<String> animalComboBox;
    private javax.swing.JButton endButton;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton menuButton;
    private javax.swing.JTextField petText;
    private javax.swing.JTextArea petTextArea;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables

    void paintComponent(Graphics g) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
